name: sChat
author: Smiley43210
main: com.github.sSuite.sChat.Main
version: 1.0
depend: [sLib]
commands:
  schat:
    description: sChat related commands.
    usage: /<command>
  whisper:
    description: Privately messages player the specified message.
    aliases: [tell, pm]
    usage: /<command> [player] [message]
  away:
    description: Sets the player as away or not.
    aliases: [afk]
    usage: /<command>
  mail:
    description: Manages player mail.
    usage: /<command>
permissions:
  schat.reload:
    description: Allows player to reload the configuration files.
    default: op
  schat.player:
    description: Allows player to manage player settings.
    default: op
  schat.mail.send:
    description: Allows player to send mail.
    default: true
  schat.mail.recieve:
    description: Allows player to receive mail.
    default: true