chat-format: <$prefix$name$suffix> $message
default-name-color: white
players:
    Smiley43210:
        prefix: $red[Example]
        suffix: $blue[suffix]$white
        name-color: green
        chat-color: white